# Title of website
title: Font Tutorials
description: The home of easy to follow tutorials on font editing software
baseurl: ""

# Adds SEO identification iaw Schema.org
type: HowTo
tagline: Easy to follow, step by step instructions on how to use font editing software

# Jekyll theme
remote_theme: pmarsceill/just-the-docs

# Add a site logo for each page, also helps SEO
logo: /assets/images/logo.png

# Makes urls easy to read
permalink: pretty

# Exclude files and folders from being processed
exclude:
    - node_modules/
    - '*.gem'
    - Gemfile
    - Gemfile.lock
    - package.json
    - package-lock.json
    - script/
    - license/
    - privacy/
    - lib/
    - bin/
    - README.md
    - Rakefile
# Adds search function
search_enabled: true
search_tokenizer_separator: '/[\s/]+/'

# Language style
markdown: kramdown

# Gems to include
gems:
    - just-the-docs
    - jekyll-seo-tag
# Plugins
plugins:
    - jekyll-remote-theme
# Auxillary link in TOC and top right Github link
aux_links:
    "Font Tutorials on GitHub":
        - "//github.com/g-wallis/font-tutorials/"
# Adds anchor links to h2-h6
heading_anchors: true

# Footer Info
footer_content: Font Tutorials are distributed under an open source <a href="/license">MIT License.<a> | Our <a href="/privacy">Privacy Policy</a>

# Search Engine Verification
webmaster_verifications:
  yandex: 0aae3dc7090ff70b

# Google Analytics Tracking
ga_tracking: UA-167494395-1